#!/usr/bin/env node

// Harvest response schemas for the NGC registry surface from the ngcsdk
// Python SDK (the archetype-2 fallback, applied to the response side only).
//
// Why: the harvested Private Artifacts (Models) definition
// (provider-dev/downloaded/ngc_models.json) declares request bodies and
// parameters for 333 operations but a 2xx response on only 30 of them - it
// is a request-side definition. StackQL projects rows from response
// schemas, so the registry/catalog surface needs them from somewhere. The
// ngcsdk wheel on PyPI ships the SDK's auto-generated data classes
// (registry/data/model/*.py: Model, ModelListResponse, ArtifactResponse,
// PaginationInfo, ...) - typed property by property, generated from the
// same API definition. This script converts them to JSON Schema
// deterministically; clean_specs.mjs then attaches them as the 200
// responses of the response-less operations (rule inject-sdk-responses).
//
// Pinned artifact: a PyPI wheel is immutable, so (version, sha256) is a
// reproducible input. The wheel itself is cached in provider-dev/downloaded/
// (gitignored); the derived provider-dev/downloaded/ngc_sdk_schemas.json is
// committed. Fails without writing on a hash mismatch or a parse failure.
//
// Usage: node provider-dev/scripts/harvest_ngc_sdk_schemas.mjs

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import zlib from 'zlib';
import { fileURLToPath } from 'url';

const NGCSDK_VERSION = '4.36.6';
const NGCSDK_WHEEL = `ngcsdk-${NGCSDK_VERSION}-py3-none-any.whl`;
const NGCSDK_URL = `https://files.pythonhosted.org/packages/3c/cf/e4901fd5a50621d3f058d0ba4f732651a86d672fb76b7a404473b2b23ac1/${NGCSDK_WHEEL}`;
const NGCSDK_SHA256 = '8cf4ce3bd071b3d2e24d40f2c66abc2c2b49022b53d400a2eb9fe6018fe3f343';
// the data-class packages harvested (path prefix inside the wheel)
const PACKAGES = ['registry/data/model/'];

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const downloadDir = path.join(repoRoot, 'provider-dev', 'downloaded');
const wheelPath = path.join(downloadDir, NGCSDK_WHEEL);
const outPath = path.join(downloadDir, 'ngc_sdk_schemas.json');
const manifestPath = path.join(downloadDir, 'download_manifest.json');

// ---------------------------------------------------------------------------
// minimal zip reader (central directory + deflate), no dependencies
// ---------------------------------------------------------------------------

function readZip(buf) {
  // locate the end-of-central-directory record
  let eocd = -1;
  for (let i = buf.length - 22; i >= Math.max(0, buf.length - 65557); i--) {
    if (buf.readUInt32LE(i) === 0x06054b50) { eocd = i; break; }
  }
  if (eocd < 0) throw new Error('not a zip file (no end-of-central-directory record)');
  const entries = buf.readUInt16LE(eocd + 10);
  let off = buf.readUInt32LE(eocd + 16);
  const files = new Map();
  for (let n = 0; n < entries; n++) {
    if (buf.readUInt32LE(off) !== 0x02014b50) throw new Error('bad central directory header');
    const method = buf.readUInt16LE(off + 10);
    const compressedSize = buf.readUInt32LE(off + 20);
    const nameLen = buf.readUInt16LE(off + 28);
    const extraLen = buf.readUInt16LE(off + 30);
    const commentLen = buf.readUInt16LE(off + 32);
    const localOff = buf.readUInt32LE(off + 42);
    const name = buf.toString('utf8', off + 46, off + 46 + nameLen);
    files.set(name, { method, compressedSize, localOff });
    off += 46 + nameLen + extraLen + commentLen;
  }
  return {
    names: [...files.keys()],
    read(name) {
      const f = files.get(name);
      if (!f) throw new Error(`no such zip entry: ${name}`);
      if (buf.readUInt32LE(f.localOff) !== 0x04034b50) throw new Error(`bad local header for ${name}`);
      const nameLen = buf.readUInt16LE(f.localOff + 26);
      const extraLen = buf.readUInt16LE(f.localOff + 28);
      const start = f.localOff + 30 + nameLen + extraLen;
      const data = buf.subarray(start, start + f.compressedSize);
      if (f.method === 0) return data.toString('utf8');
      if (f.method === 8) return zlib.inflateRawSync(data).toString('utf8');
      throw new Error(`unsupported zip compression method ${f.method} for ${name}`);
    }
  };
}

// ---------------------------------------------------------------------------
// data-class parser: the SDK classes are generated by one template, so the
// parse is a small set of anchored patterns
// ---------------------------------------------------------------------------

const SCALAR_TYPES = {
  int: { type: 'integer' },
  long: { type: 'integer', format: 'int64' },
  float: { type: 'number' },
  bool: { type: 'boolean' },
  string_types: { type: 'string' },
  str: { type: 'string' },
  dict: { type: 'object' },
  list: { type: 'array' }
};

function parseDataClass(source, fileName) {
  const classMatch = source.match(/^class (\w+)\(object\):\n(?:\s+"""([^"]*)""")?/m);
  if (!classMatch) {
    // enum-style modules and helpers carry no propDict constructor
    if (!/def __init__\(self, propDict=None\)/.test(source)) return null;
    throw new Error(`${fileName}: unrecognised class layout`);
  }
  const [, className, classDoc = ''] = classMatch;
  const props = {};
  // property names, in declaration order, from the constructor
  const initBody = source.slice(source.indexOf('def __init__(self, propDict=None)'));
  const initEnd = initBody.search(/\n    @property/);
  const init = initEnd > 0 ? initBody.slice(0, initEnd) : initBody;
  for (const m of init.matchAll(/self\.(\w+) = \(/g)) props[m[1]] = {};
  for (const name of Object.keys(props)) {
    const schema = {};
    // list element class: [ Foo(i) for i in propDict["name"] ]
    const elem = init.match(new RegExp(`else \\[ (\\w+)\\(i\\)\\s+for i in propDict\\["${name}"\\] \\]`));
    // setter type guard
    const setter = source.match(new RegExp(`@${name}\\.setter\\n\\s+def ${name}\\(self, value\\):\\n([\\s\\S]*?)(?=\\n    @|\\n    def toDict)`));
    if (!setter) throw new Error(`${fileName}: no setter for ${className}.${name}`);
    const guard = setter[1].match(/isinstance\(value, (\w+)\)/);
    if (!guard) throw new Error(`${fileName}: no type guard for ${className}.${name}`);
    const t = guard[1];
    if (t === 'list') {
      schema.type = 'array';
      schema.items = elem ? { $ref: `#/components/schemas/${elem[1]}` } : { type: 'string' };
    } else if (SCALAR_TYPES[t]) {
      Object.assign(schema, SCALAR_TYPES[t]);
    } else {
      schema.$ref = `#/components/schemas/${t}`;
    }
    // getter docstring: """<Type>: <description>"""
    const getter = source.match(new RegExp(`@property\\n\\s+def ${name}\\(self\\):\\n\\s+"""([^"]*)"""`));
    if (getter) {
      const doc = getter[1].trim().replace(/^[\w<>]+:\s*/, '');
      if (doc && !schema.$ref) schema.description = doc;
      else if (doc && schema.$ref) schema['x-description'] = doc; // siblings of $ref are ignored by resolvers
    }
    props[name] = schema;
  }
  return { className, schema: { type: 'object', ...(classDoc.trim() ? { description: classDoc.trim() } : {}), properties: props } };
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

fs.mkdirSync(downloadDir, { recursive: true });
let wheel;
if (fs.existsSync(wheelPath)) {
  wheel = fs.readFileSync(wheelPath);
} else {
  console.log(`Fetching ${NGCSDK_URL}`);
  const res = await fetch(NGCSDK_URL, { signal: AbortSignal.timeout(120000) });
  if (!res.ok) {
    console.error(`Error: HTTP ${res.status} from ${NGCSDK_URL} - nothing written`);
    process.exit(1);
  }
  wheel = Buffer.from(await res.arrayBuffer());
}
const sha256 = crypto.createHash('sha256').update(wheel).digest('hex');
if (sha256 !== NGCSDK_SHA256) {
  console.error(`Error: ${NGCSDK_WHEEL} sha256 ${sha256} does not match the pinned ${NGCSDK_SHA256} - nothing written`);
  process.exit(1);
}
if (!fs.existsSync(wheelPath)) fs.writeFileSync(wheelPath, wheel);

const zip = readZip(wheel);
const schemas = {};
const skipped = [];
for (const name of zip.names.sort()) {
  if (!PACKAGES.some((p) => name.startsWith(p)) || !name.endsWith('.py') || name.endsWith('__init__.py')) continue;
  const parsed = parseDataClass(zip.read(name), name);
  if (!parsed) { skipped.push(name); continue; }
  if (schemas[parsed.className]) throw new Error(`duplicate data class ${parsed.className}`);
  schemas[parsed.className] = parsed.schema;
}

// every $ref must resolve within the harvested set
const missing = new Set();
for (const [cls, schema] of Object.entries(schemas)) {
  for (const [prop, s] of Object.entries(schema.properties)) {
    const ref = s.$ref || s.items?.$ref;
    if (ref && !schemas[ref.split('/').pop()]) missing.add(`${cls}.${prop} -> ${ref.split('/').pop()}`);
  }
}
if (missing.size > 0) {
  console.error(`Error: ${missing.size} unresolved data-class reference(s) - nothing written:`);
  for (const m of [...missing].sort()) console.error(`  ${m}`);
  process.exit(1);
}

const out = {
  package: 'ngcsdk',
  version: NGCSDK_VERSION,
  wheel: NGCSDK_WHEEL,
  url: NGCSDK_URL,
  sha256: NGCSDK_SHA256,
  packages: PACKAGES,
  classes: Object.keys(schemas).length,
  enumModulesSkipped: skipped.map((n) => n.split('/').pop().replace(/\.py$/, '')),
  schemas
};
fs.writeFileSync(outPath, JSON.stringify(out, null, 2) + '\n');

const manifest = fs.existsSync(manifestPath) ? JSON.parse(fs.readFileSync(manifestPath, 'utf8')) : { files: {} };
manifest.ngcSdk = {
  package: 'ngcsdk',
  version: NGCSDK_VERSION,
  url: NGCSDK_URL,
  sha256: NGCSDK_SHA256,
  derived: 'ngc_sdk_schemas.json',
  packages: PACKAGES,
  classes: Object.keys(schemas).length,
  note: 'response schemas for the registry/catalog surface: the harvested models definition declares no 2xx responses on most operations; the SDK data classes are the pinned response-side source (archetype-2 fallback, response side only)'
};
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

console.log(`Harvested ${Object.keys(schemas).length} data classes from ${NGCSDK_WHEEL} (${skipped.length} enum/helper modules skipped) -> ${outPath}`);
